# PyInstaller spec — one-file executable for macOS, Windows, and Linux.
#
# Build:
#   macOS   →  ./build.sh          →  dist/Ubiquity.app  +  dist/Ubiquity.dmg
#   Windows →  build.bat           →  dist/ubiquity.exe
#              build.bat installer →  dist/UbiquitySetup.exe  (no-admin Inno Setup)
#   Linux   →  ./build.sh          →  dist/ubiquity

import sys

block_cipher = None

hidden_imports = [
    # watchdog platform backends (loaded at runtime via importlib)
    'watchdog.observers',
    'watchdog.observers.fsevents',
    'watchdog.observers.inotify',
    'watchdog.observers.winapi',
    'watchdog.observers.polling',
    # pystray platform backends
    'pystray._darwin',
    'pystray._win32',
    'pystray._xorg',
    # pyperclip platform helpers
    'pyperclip.handlers',
    # settings dialog
    'tkinter',
    'tkinter.filedialog',
]

a = Analysis(
    ['ubiquity.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=hidden_imports,
    hookspath=['hooks'],
    runtime_hooks=[],
    excludes=[
        # google.cloud hook crashes when google-cloud-core is absent
        'google', 'google.cloud',
        # packages installed in the global env but not used by Ubiquity
        # (auto-generated by diffing pip list vs requirements.txt)
        'absl_py', 'addict', 'aiohappyeyeballs', 'aiohttp', 'aiosignal',
        'alabaster', 'annotated_types', 'ansi2html', 'anyio', 'apheleia',
        'appdirs', 'arrow', 'attrs', 'audioread', 'babel', 'beautifulsoup4',
        'bleak', 'bless', 'blinker', 'certifi', 'chardet', 'charset_normalizer',
        'click', 'click_plugins', 'cligj', 'cloudpickle', 'codecarbon',
        'configargparse', 'contourpy', 'cryptography', 'cssselect',
        'customtkinter', 'cycler', 'cython', 'daemonocle', 'darkdetect',
        'dash', 'dash_core_components', 'dash_html_components', 'dash_table',
        'decorator', 'distro', 'dnspython', 'docker_pycreds', 'docutils',
        'et_xmlfile', 'farama_notifications', 'fastapi', 'fastjsonschema',
        'ffmpeg_python', 'filelock', 'fiona', 'flask', 'fonttools',
        'frozendict', 'frozenlist', 'fsspec', 'future', 'fuzzywuzzy',
        'geoalchemy2', 'geopandas', 'gguf', 'gitdb', 'gitpython',
        'googlesearch_python', 'greenlet', 'grpcio', 'gymnasium',
        'h11', 'hid', 'html5lib', 'httpcore', 'httpx', 'huggingface_hub',
        'hyperpyyaml', 'idna', 'imageio', 'imageio_ffmpeg', 'imagesize',
        'itsdangerous', 'jinja2', 'joblib', 'jsonschema',
        'jsonschema_specifications', 'jupyter_core', 'kconfiglib', 'kiwisolver',
        'lazy_loader', 'librosa', 'lightning_utilities', 'llvmlite', 'lpips',
        'lxml', 'markdown', 'markupsafe', 'matplotlib', 'moviepy', 'mpmath',
        'msgpack', 'msgpack_python', 'msgpack_rpc_python', 'multidict',
        'multitasking', 'nbformat', 'nest_asyncio', 'netifaces', 'networkx',
        'nibabel', 'noisereduce', 'ntplib', 'numba', 'numpy', 'open3d',
        'openai', 'opencv_contrib_python', 'opencv_python', 'openpyxl',
        'pandas', 'pathtools', 'peewee', 'phue', 'piq', 'plotly', 'pooch',
        'proglog', 'propcache', 'protobuf', 'psutil', 'psycopg2_binary',
        'py_cpuinfo', 'pyarmor', 'pycryptodome', 'pydantic', 'pydantic_core',
        'pydicom', 'pygame', 'pygments', 'pymongo', 'pynvml', 'pyparsing',
        'pypdf', 'pypdf2', 'pyproj', 'pyqt5', 'pyqt5_qt5', 'pyqt5_sip',
        'pyqtgraph', 'pyquaternion', 'pyros_genmsg', 'pyserial',
        'python_dateutil', 'python_dotenv', 'python_multipart', 'python_pam',
        'pytz', 'pywizlight', 'pyyaml', 'qimage2ndarray', 'qtawesome', 'qtpy',
        'readability_lxml', 'referencing', 'regex', 'requests',
        'requests_toolbelt', 'retrying', 'rpds_py', 'ruamel.yaml',
        'ruamel.yaml.clib', 'safetensors', 'scikit_learn', 'scipy',
        'screeninfo', 'seaborn', 'sentencepiece', 'sentry_sdk', 'setproctitle',
        'shapely', 'simpleitk', 'smmap', 'sniffio', 'snowballstemmer',
        'socketio', 'sounddevice', 'soundfile', 'soupsieve', 'soxr',
        'speechbrain', 'sphinx', 'sphinx_rtd_theme', 'sqlalchemy',
        'stable_baselines3', 'starlette', 'sympy', 'tenacity', 'tensorboard',
        'tensorboard_data_server', 'threadpoolctl', 'tkinter_tooltip',
        'tokenizers', 'toml', 'torch', 'torch_ema', 'torch_fidelity',
        'torch_geometric', 'torchaudio', 'torchmetrics', 'torchserve',
        'torchvision', 'tornado', 'traitlets', 'transformers', 'tzdata',
        'unidecode', 'uritools', 'urlextract', 'urllib3', 'uvicorn', 'wandb',
        'webencodings', 'werkzeug', 'yarl', 'yfinance',
    ],
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name='ubiquity',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    # No console window — this is a tray app, not a CLI tool.
    console=False,
    onefile=True,
    icon='assets/ubiquity.ico',
)

if sys.platform == 'darwin':
    app = BUNDLE(
        exe,
        name='Ubiquity.app',
        icon='assets/ubiquity.icns',
        bundle_identifier='com.ubiquity.sync',
        info_plist={
            # Hide from Dock — the app lives entirely in the menu bar.
            'LSUIElement': True,
            'NSHighResolutionCapable': True,
            'CFBundleShortVersionString': '1.0',
        },
    )
